"""Added watch history table

Revision ID: 0bd73e312c3b
Revises: 1717abe76786
Create Date: 2024-11-23 22:11:44.663031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bd73e312c3b'
down_revision = '1717abe76786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user__watch__history',
    sa.Column('user_id', sa.String(length=45), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('watch_date', sa.Date(), nullable=True),
    sa.Column('favorite', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'movie_id')
    )
    with op.batch_alter_table('user__reviews', schema=None) as batch_op:
        batch_op.drop_index('movie_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user__reviews', schema=None) as batch_op:
        batch_op.create_index('movie_id', ['movie_id'], unique=True)

    op.drop_table('user__watch__history')
    # ### end Alembic commands ###
