"""Initial commit

Revision ID: 1717abe76786
Revises: 
Create Date: 2024-11-23 22:10:41.439174

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1717abe76786'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user__watch__history')
    with op.batch_alter_table('user__reviews', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['movie_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user__reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.create_table('user__watch__history',
    sa.Column('user_id', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('movie_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('watch_date', sa.DATE(), nullable=True),
    sa.Column('favorite', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='user__watch__history_ibfk_1'),
    sa.PrimaryKeyConstraint('user_id', 'movie_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
