"""empty message

Revision ID: 499ca19039ef
Revises: 500101cdc1ea
Create Date: 2025-02-25 00:24:19.739346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '499ca19039ef'
down_revision = '500101cdc1ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firsttimesetup', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('firsttimesetup')

    # ### end Alembic commands ###
