"""empty message

Revision ID: 500101cdc1ea
Revises: bfb76b64a54b
Create Date: 2025-02-20 21:42:26.678992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '500101cdc1ea'
down_revision = 'bfb76b64a54b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(length=45), autoincrement=False, nullable=False),
    sa.Column('firsttimesetup', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user__info',
    sa.Column('user_id', sa.String(length=45), nullable=False),
    sa.Column('genre', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'genre')
    )
    op.create_table('user__reviews',
    sa.Column('user_id', sa.String(length=45), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('movie_rating', sa.Integer(), nullable=True),
    sa.Column('movie_review', sa.String(length=10000), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'movie_id')
    )
    op.create_table('user__watch__history',
    sa.Column('user_id', sa.String(length=45), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('watch_date', sa.Date(), nullable=True),
    sa.Column('favorite', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'movie_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user__watch__history')
    op.drop_table('user__reviews')
    op.drop_table('user__info')
    op.drop_table('users')
    # ### end Alembic commands ###
