"""Change date to datetime

Revision ID: e9219dc48118
Revises: 499ca19039ef
Create Date: 2025-04-10 11:41:47.394050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9219dc48118'
down_revision = '499ca19039ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user__watch__history', schema=None) as batch_op:
        batch_op.alter_column('watch_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user__watch__history', schema=None) as batch_op:
        batch_op.alter_column('watch_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
